apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSCluster
metadata:
  name: {{ .Values.clusterName }}
  namespace: default
spec:
  region: {{ .Values.region }}
  sshKeyName: {{ .Values.sshKeyName }}
